name: Deploy Wiki

on:
  workflow_dispatch:
  push:

jobs:
  deploy-wiki:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip sdist wheel
        pip install -r requirements.txt

    - name: Build Pages (replace stubs)
      run: |
        python ./build_wiki.py

    - name: Push Wiki Changes
      uses: Andrew-Chen-Wang/github-wiki-action@v2
      env:
        WIKI_DIR: wiki/
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_MAIL: ${{ secrets.EMAIL }}
        GH_NAME: ${{ github.repository_owner }}
